{"name": "Логин пользователя", "status": "broken", "statusDetails": {"message": "requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)", "trace": "C:\\Users\\ilme5\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\requests\\models.py:974: in json\n    return complexjson.loads(self.text, **kwargs)\n        kwargs     = {}\n        self       = <Response [404]>\nC:\\Users\\ilme5\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\__init__.py:346: in loads\n    return _default_decoder.decode(s)\n        cls        = None\n        kw         = {}\n        object_hook = None\n        object_pairs_hook = None\n        parse_constant = None\n        parse_float = None\n        parse_int  = None\n        s          = ('<html>\\r\\n'\n '<head><title>404 Not Found</title></head>\\r\\n'\n '<body>\\r\\n'\n '<center><h1>404 Not Found</h1></center>\\r\\n'\n '<hr><center>nginx/1.18.0 (Ubuntu)</center>\\r\\n'\n '</body>\\r\\n'\n '</html>\\r\\n')\nC:\\Users\\ilme5\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py:337: in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n        _w         = <built-in method match of re.Pattern object at 0x0000020612D4F440>\n        s          = ('<html>\\r\\n'\n '<head><title>404 Not Found</title></head>\\r\\n'\n '<body>\\r\\n'\n '<center><h1>404 Not Found</h1></center>\\r\\n'\n '<hr><center>nginx/1.18.0 (Ubuntu)</center>\\r\\n'\n '</body>\\r\\n'\n '</html>\\r\\n')\n        self       = <json.decoder.JSONDecoder object at 0x0000020612DA29C0>\nC:\\Users\\ilme5\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py:355: in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\nE   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n        idx        = 0\n        s          = ('<html>\\r\\n'\n '<head><title>404 Not Found</title></head>\\r\\n'\n '<body>\\r\\n'\n '<center><h1>404 Not Found</h1></center>\\r\\n'\n '<hr><center>nginx/1.18.0 (Ubuntu)</center>\\r\\n'\n '</body>\\r\\n'\n '</html>\\r\\n')\n        self       = <json.decoder.JSONDecoder object at 0x0000020612DA29C0>\n\nDuring handling of the above exception, another exception occurred:\nconftest.py:11: in user_data\n    token = response.json()['accessToken']\n        payload    = {'email': 'tammycline@example.net', 'name': 'Gregory', 'password': '(pd4Mpbq^L'}\n        response   = <Response [404]>\nC:\\Users\\ilme5\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\requests\\models.py:978: in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\nE   requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n        kwargs     = {}\n        self       = <Response [404]>"}, "description": "Проверка логин с неверным паролем пользователя,проверка кода и текста ответа", "start": 1719837918521, "stop": 1719837918521, "uuid": "514c5157-5cb1-45d1-a158-71e677ee7103", "historyId": "0c088f105c0c5bc5fddf48b28f2f74ff", "testCaseId": "0c088f105c0c5bc5fddf48b28f2f74ff", "fullName": "tests.test_login_user.TestLoginUser#test_login_user_incorrect_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-8VJF26I"}, {"name": "thread", "value": "22712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}