{"name": "Получение заказов конкретного пользователя", "status": "broken", "statusDetails": {"message": "requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)", "trace": "C:\\Users\\ilme5\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\requests\\models.py:974: in json\n    return complexjson.loads(self.text, **kwargs)\n        kwargs     = {}\n        self       = <Response [404]>\nC:\\Users\\ilme5\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\__init__.py:346: in loads\n    return _default_decoder.decode(s)\n        cls        = None\n        kw         = {}\n        object_hook = None\n        object_pairs_hook = None\n        parse_constant = None\n        parse_float = None\n        parse_int  = None\n        s          = ('<html>\\r\\n'\n '<head><title>404 Not Found</title></head>\\r\\n'\n '<body>\\r\\n'\n '<center><h1>404 Not Found</h1></center>\\r\\n'\n '<hr><center>nginx/1.18.0 (Ubuntu)</center>\\r\\n'\n '</body>\\r\\n'\n '</html>\\r\\n')\nC:\\Users\\ilme5\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py:337: in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n        _w         = <built-in method match of re.Pattern object at 0x0000020612D4F440>\n        s          = ('<html>\\r\\n'\n '<head><title>404 Not Found</title></head>\\r\\n'\n '<body>\\r\\n'\n '<center><h1>404 Not Found</h1></center>\\r\\n'\n '<hr><center>nginx/1.18.0 (Ubuntu)</center>\\r\\n'\n '</body>\\r\\n'\n '</html>\\r\\n')\n        self       = <json.decoder.JSONDecoder object at 0x0000020612DA29C0>\nC:\\Users\\ilme5\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\json\\decoder.py:355: in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\nE   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n        idx        = 0\n        s          = ('<html>\\r\\n'\n '<head><title>404 Not Found</title></head>\\r\\n'\n '<body>\\r\\n'\n '<center><h1>404 Not Found</h1></center>\\r\\n'\n '<hr><center>nginx/1.18.0 (Ubuntu)</center>\\r\\n'\n '</body>\\r\\n'\n '</html>\\r\\n')\n        self       = <json.decoder.JSONDecoder object at 0x0000020612DA29C0>\n\nDuring handling of the above exception, another exception occurred:\nconftest.py:11: in user_data\n    token = response.json()['accessToken']\n        payload    = {'email': 'zpowell@example.org', 'name': 'Karen', 'password': '6(+2W^8dby'}\n        response   = <Response [404]>\nC:\\Users\\ilme5\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\requests\\models.py:978: in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\nE   requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n        kwargs     = {}\n        self       = <Response [404]>"}, "description": "Авторизованный пользователь, проверка кода и текста ответа", "start": 1719837917409, "stop": 1719837917409, "uuid": "940876ad-1370-437d-ba50-83b21f738179", "historyId": "9dbcee445738beeb3e132f9758e29574", "testCaseId": "9dbcee445738beeb3e132f9758e29574", "fullName": "tests.test_get_user_orders.TestGetUserOrders#test_get_orders_with_authorization", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetUserOrders"}, {"name": "host", "value": "DESKTOP-8VJF26I"}, {"name": "thread", "value": "22712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}